---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop my-project-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm my-project-container
      ignore_errors: yes

    - name: remove my-project-image
      command: docker rmi my-project-image
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t my-project-image .

    - name: create tag to image
      command: docker tag my-project-image triple3a/my-project-image

    - name: push image to dockerhub
      command: docker push triple3a/my-project-image

    - name: remove docker created images
      command: docker rmi my-project-image triple3a/my-project-image
