---
- name: Create deployment and Services
  hosts: kubernetes
  # become: true
  user: ubuntu

  tasks:
    - name: create a deployment
      command: kubectl apply -f k8s-deploy.yml

    - name: create a service
      command: kubectl apply -f k8s-service.yml
