apiVersion: v1
kind: Service
metadata:
  name: comingsoon-service
  labels:
    app: comingsoon-devops-project
spec:
  selector:
    app: comingsoon-devops-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32300
